### ISSUE TITLE
Lunch Issue

### ISSUE THREAD

**Issue by Gityashi** [IntroToCode/Spring21_Recipes_Codemates12#2]
## 💬 Discussion topic

Decide on a recipe for lunch

## ❗ Potential issues

- Do we have enough to serve all 5 of us?
- Time to prepare
- Dietary Concerns / Food Preferences

## 👥 People to consult

@anna586 @mcroeller1 @peterkossar @lmjchen

**Comment by mcroeller1** [comment]
I don't have any dietary concerns. I don't like olives or raw tomatoes :)

**Comment by Gityashi** [comment]
Suggesting chicken salad sandwiches for lunch.  Scales well for 5 people, has protein.

**Comment by lmjchen** [comment]
> Suggesting chicken salad sandwiches for lunch. Scales well for 5 people, has protein.

Good idea! Healthy food.

**Comment by mcroeller1** [comment]
I like chicken salad sandwiches. Do we have any vegetarians on our team? I am not one, but just wondering. @peterkossar and @anna586 may need to weigh in here (although based on their nacho suggestions I think they are not vegetarian haha)

**Comment by peterkossar** [comment]
Chicken salad sammich sounds great! I'm not vegetarian and have no dietary restrictions :)

**Comment by Gityashi** [comment]
OK!  I'm starting a pull request for Lunch for a recipe for chicken salad sandwiches.

Would love if folks could contribute the following as part of their subsequent commits:
@mcroeller1   - Add some suggested sandwich toppings to the recipe
@anna586     - Add a suggested side to serve the sandwiches with
@lmjchen       - Add a suggested beverage to serve the sandwiches with
@peterkossar   - Add in suggested recipe alterations, like adding grapes, nuts, or other flavors into the salad mix

Thanks!

**Comment by peterkossar** [comment]
I added some suggested recipe alterations
