### ISSUE TITLE
Breakfast Issue

### ISSUE THREAD

**Issue by mcroeller1** [IntroToCode/Spring21_Recipes_Codemates12#6]
## 💬 Discussion topic

What time do people get up for Breakfast?

## ❗ Potential issues

Do we have late risers?
Can this turn into brunch?

## 👥 People to consult

@anna586 @peterkossar @Gityashi @lmjchen 

## 📃 Details

What time does everybody wake up in the morning so breakfast can be ready on time?

**Comment by lmjchen** [comment]
💬 Discussion topic
What time do people get up for Breakfast?
 8am on weekday
11am on weeked

❗ Potential issues
Do we have late risers?
Yes.
Can this turn into brunch?
Great Idea for Sunday brunch
👥 People to consult
@anna586 @peterkossar @Gityashi @lmjchen

📃 Details
What time does everybody wake up in the morning so breakfast can be ready on time?

**Comment by Gityashi** [comment]
As a late riser, I have a strong preference for weekend brunch!

**Comment by peterkossar** [comment]
weekend brunch ftw!
