### ISSUE TITLE
Dinner issue

### ISSUE THREAD

**Issue by anna586** [IntroToCode/Spring21_Recipes_Codemates12#7]
## 💬 Discussion topic

Decide on a simple dinner recipe.

## ❗ Potential issues

- Is it a simple recipe we can make after a busy day of work
- Are ingredients in clear quantities
- Time to prepare
- Dietary restrictions
- Could someone who has never seen a grilled cheese prepare this dish

## 👥 People to consult

Text

## 📃 Details

Text

**Comment by mcroeller1** [comment]
Have we all agreed that a grilled cheese is the right recipe for dinner? Might not be the most balanced meal. I'm ok with it, but was wondering what people thought.

**Comment by peterkossar** [comment]
We can deck out a grilled cheese! Tomato and some other veggies and bacon (for the meat eaters) can be very filling and yummy.

**Comment by Gityashi** [comment]
I agree with Peter.  We can always add on to the recipe and fill them out.  Or a healthy side could work, like a salad.  Grilled cheese and tomato soup are go-to comfort foods!

**Comment by mcroeller1** [comment]
Sounds good - especially if we add the tomato soup! 🤤

**Comment by mcroeller1** [comment]
I created a section in our dinner recipe for type of bread and type of cheese. @peterkossar do you want to pick the type of bread? @anna586 how about the type of cheese? @lmjchen do you want to suggest a salad or a vegetable to go with this dinner?

**Comment by peterkossar** [comment]
I added type of bread into the pull request.

**Comment by lmjchen** [comment]
I have merged the dinner recipe into the main.
