### ISSUE TITLE
Breakfast Recipe

### ISSUE THREAD

**Issue by mcroeller1** [IntroToCode/Spring21_Recipes_Codemates12#8]
## 💬 Discussion topic

What do people typically like to eat for breakfast?

## ❗ Potential issues

Do people typically like a smaller breakfast or start with a big meal?
Do people like sweet breakfast or savory.

## 👥 People to consult

@anna586 @peterkossar @lmjchen @Gityashi 

## 📃 Details

Let's agree on what people would like to eat for breakfast.

**Comment by mcroeller1** [comment]
Some ideas: scrambled eggs, pancakes, yoghurt with granola and fruit, toast with jam, pastries

**Comment by Gityashi** [comment]
No preference on my end re: sweet vs. savory.  We just need 1 go-to recipe that will feed all 5 of us.

Something like pancakes w/ a selection of toppings, or a large frittata could work well.  Per our other issue chain, aiming for a weekend brunch gives the cook more time in the morning to prep!

But I like the idea of including serving suggestions for sides with the recipe.

**Comment by peterkossar** [comment]
No preference here! Love the idea of pancakes with a selection of toppings.
