### ISSUE TITLE
Breakfast Beverage?

### ISSUE THREAD

**Issue by mcroeller1** [IntroToCode/Spring21_Recipes_Codemates12#9]
## 💬 Discussion topic

What do people like to drink for Breakfast?

## ❗ Potential issues

Do we have people who require coffee?
If people require coffee -> what kind? Espresso? Latte? Drip coffee?
Do we have coffee haters?
Are some people lactose intolerant and want milk alternatives?

## 👥 People to consult

@anna586 @peterkossar @lmjchen @Gityashi @mcroeller1 

## 📃 Details

Please let me know what your preferences are for breakfast beverages

**Comment by peterkossar** [comment]
black coffee for me is a staple in the morning
